-- Drop all tables with CASCADE to handle all dependencies
DROP TABLE IF EXISTS DECK_CARD CASCADE;
DROP TABLE IF EXISTS COLLECTION_CARD CASCADE;
DROP TABLE IF EXISTS DECK CASCADE;
DROP TABLE IF EXISTS COLLECTION CASCADE;
DROP TABLE IF EXISTS CARD_PRINTING CASCADE;
DROP TABLE IF EXISTS CARD CASCADE;
DROP TABLE IF EXISTS CARD_SET CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
  USER_ID SERIAL PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  DATE_JOINED DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE CARD (
  CARD_ID SERIAL PRIMARY KEY,
  CARD_NAME VARCHAR(100) NOT NULL,
  CARD_TYPE VARCHAR(50) NOT NULL,
  DOMAIN VARCHAR(50),
  ENERGY INT CHECK (ENERGY >= 0),
  POWER INT CHECK (POWER >= 0),
  MIGHT INT CHECK (MIGHT >= 0),
  ABILITY_TEXT TEXT,
  ARTIST VARCHAR(100) NOT NULL,
  COLLECTOR_NUMBER VARCHAR(80) NOT NULL,
  FLAVOR_TEXT TEXT
);

CREATE TABLE CARD_SET (
  SET_ID SERIAL PRIMARY KEY,
  SET_NAME VARCHAR(100) NOT NULL,
  SET_CODE VARCHAR(10) NOT NULL UNIQUE,
  RELEASE_DATE DATE NOT NULL,
  TOTAL_CARDS INTEGER CHECK (TOTAL_CARDS > 0),
  DESCRIPTION TEXT
);

CREATE TABLE CARD_PRINTING (
  PRINTING_ID VARCHAR(20) PRIMARY KEY,
  CARD_ID INT NOT NULL,
  SET_ID INT NOT NULL,
  RARITY VARCHAR(20) NOT NULL,
  FOIL BOOLEAN DEFAULT FALSE,
  ALT_ART BOOLEAN DEFAULT FALSE,
  OVERNUMBERED BOOLEAN DEFAULT FALSE,
  SIGNED BOOLEAN DEFAULT FALSE,
  RELEASE_DATE DATE NOT NULL,
  IMAGE_URL VARCHAR(255),
  FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID) ON DELETE CASCADE,
  FOREIGN KEY (SET_ID) REFERENCES CARD_SET(SET_ID) ON DELETE CASCADE
);

CREATE TABLE COLLECTION (
  COLLECTION_ID SERIAL PRIMARY KEY,
  USER_ID INT NOT NULL,
  COLLECTION_NAME VARCHAR(100) DEFAULT 'My Collection',
  DATE_CREATED DATE NOT NULL DEFAULT CURRENT_DATE,
  IS_PRIMARY BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE COLLECTION_CARD (
  COLLECTION_ID INT NOT NULL,
  PRINTING_ID VARCHAR(20) NOT NULL,
  QUANTITY INT NOT NULL CHECK (QUANTITY > 0) DEFAULT 1,
  CONDITION VARCHAR(20) CHECK (CONDITION IN ('Mint', 'Near Mint', 'Excellent', 'Good', 'Played', 'Poor')),
  DATE_ADDED DATE NOT NULL DEFAULT CURRENT_DATE,
  PRIMARY KEY (COLLECTION_ID, PRINTING_ID),
  FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(COLLECTION_ID) ON DELETE CASCADE,
  FOREIGN KEY (PRINTING_ID) REFERENCES CARD_PRINTING(PRINTING_ID) ON DELETE CASCADE
);

CREATE TABLE DECK (
  DECK_ID SERIAL PRIMARY KEY,
  USER_ID INT NOT NULL,
  DECK_NAME VARCHAR(100) NOT NULL,
  PRIMARY_DOMAIN VARCHAR(20),
  DATE_CREATED DATE NOT NULL DEFAULT CURRENT_DATE,
  LAST_MODIFIED DATE NOT NULL DEFAULT CURRENT_DATE,
  DESCRIPTION TEXT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE DECK_CARD (
  DECK_ID INT NOT NULL,
  PRINTING_ID VARCHAR(20) NOT NULL,
  QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
  PRIMARY KEY (DECK_ID, PRINTING_ID),
  FOREIGN KEY (DECK_ID) REFERENCES DECK(DECK_ID) ON DELETE CASCADE,
  FOREIGN KEY (PRINTING_ID) REFERENCES CARD_PRINTING(PRINTING_ID) ON DELETE CASCADE
);